name: macOS Bug Report ðŸ›
description: Add a new bug report for Mimir on macOS
title: "[Bug][macOS]: Add a title for this bug"
labels: ["ðŸž bug", "âš ï¸ needs review", "ðŸ–¥ macOS"]
assignees:
  - gdavis
body:
  - type: markdown
    attributes:
      value: |
        **âš ï¸ Remember to add a short title for your bug above! â¬†ï¸**
        
        # ðŸ–¥ðŸ› Report a Bug
        Use this form to submit a new bug for the Mimir macOS app. Thank you for taking the time out of your day to help improve the app! :heart:
        
  - type: checkboxes
    id: unique
    attributes:
      label: Are you sure this is a new issue?
      description: Please be sure this is a new issue before submitting. Use the search bar in the [Issues](https://github.com/gdavis/Mimir-Feedback/issues) tab to check if this bug has already been reported.
      options:
        - label: I have confirmed this is a new issue
          required: true
  - type: input
    id: macos
    attributes:
      label: macOS Version
      description: What version of macOS are you on? This can be found under ï£¿ > About This Mac.
      placeholder: ex. Big Sur 11.6.4
    validations:
      required: true
  - type: input
    id: mac
    attributes:
      label: Your Mac
      description: What kind of Mac are you using? This can be found under ï£¿ > About This Mac.
      placeholder: ex. MacBook Pro (Retina, 15-inch, Mid 2014)
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: App Version
      description: What version of the app are you using? This can be found in the app under the 'About Mimir' menu item.
      placeholder: ex. 1.5.0 (101)
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe in detail how the bug occured. The more detail the better.
      placeholder: "ex: When I try to import a podcast, an error message appears and says: 'that is not a valid RSS feed'"
    validations:
      required: true
  - type: input
    id: prevalence
    attributes:
      label: Bug prevalence
      description: "How often do you encounter this bug?"
      placeholder: "ex: Always, rarely, only during Fimbulwinter"
    validations:
      required: false
  - type: textarea
    id: reproduction
    attributes:
      label: How does it happen?
      description: Provide a series of steps that will make this bug occur.
      placeholder: |
        1. Open the app
        2. Click 'My Favorite Podcast' from the library sidebar
        3. Click the play button for episode 'Doing Things and Stuff'
        4. Observe that the app shows the error 'Not a real podcast'
    validations:
      required: false
  - type: textarea
    id: media
    attributes:
      label: Add screenshots or video
      description: |
        Copy and paste in any relevant screenshots or video that demonstrate the issue. 
        [How to take a screenshot on macOS](https://support.apple.com/en-us/HT201361) 
        [How to record your screen on macOS](https://support.apple.com/en-us/HT208721)
  - type: textarea
    id: extra
    attributes:
      label: Anything else?
      description: Add any extra information that might be relevant for this bug report.
      placeholder: "I hope this gets fixed before Ragnarok."
