name: macOS Bug Report
description: Add a new bug report for the Mimir macOS app
title: "[Bug][macOS] "
labels: ["🐞 bug", "⚠️ needs review", "🖥 macOS"]
assignees:
  - gdavis
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: unique
    attributes:
      label: Are you sure this is a new issue?
      description: By submitting this issue, you confirm that you have searched for this bug in other open issues and confirmed it is unique.
      options:
        - label: I have confirmed this is a new issue
          required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: platform
    attributes:
      label: macOS Version
      description: Which macOS version are you using?
      options:
        - Monterey
        - Big Sur
        - Catalina
    validations:
      required: false
  - type: dropdown
    id: platform
    attributes:
      label: What kind of Mac are you using?
      options:
        - macMini
        - MacBook Pro
        - MacBook Air
        - Mac Pro
        - Mac Studio
        - iMac
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of the app are you using? This can be found in the About window.
      placeholder: ex. 1.5.0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe in detail how the bug occured. The more detail the better.
      placeholder: "Ex: When I try to import a podcast, an error message appears and says: 'that is not a valid RSS feed'"
    validations:
      required: true
  - type: input
    id: prevalence
    attributes:
      label: Bug prevalence
      description: "How often do you encounter this bug?"
      placeholder: "Ex: Always, rarely, every 6th sunday in April"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How does it happen?
      description: Provide a series of steps that will make this bug occur.
      placeholder: |
        Example: 
        1. Open the app
        2. Click 'My Favorite Podcast' from the library sidebar
        3. Click the play button for episode 'Doing Things and Stuff'
        4. Observe that the app shows the error 'Not a real podcast'
    validations:
      required: true
  - type: textarea
    id: media
    attributes:
      label: Add screenshots or video
      description: Copy and paste in any relevant screenshots or video that demonstrate the issue. [How to record your screen on macOS](https://support.apple.com/en-us/HT208721)
  - type: textarea
    id: extra
    attributes:
      label: Anything else?
      description: Add any extra information that might be relevant for this bug report.
      placeholder: "I hope this gets fixed before Ragnarok."
