name: Assign New Issues to Feedback Project
on:
  issues:
    types:
      - opened

# map fields with customized labels
env:
  needs_review: ⚠Needs Review
  todo: Todo
  done: Done
  in_progress: In Progress

jobs:
  issue_opened:
    name: issue_opened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'opened')
    steps:
      - name: Move issue to ${{ env.needs_review }}
        uses: leonsteinhaeuser/project-beta-automations@v1.2.1
        with:
          gh_app_secret_key: ${{ secrets.MY_GITHUB_TOKEN }}
          user: gdavis
          # organization: sample-org
          project_id: 3
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.needs_review }} # Target status
